#pragma once

typedef enum BuiltinPrimitiveType {
    BUILTIN_PRIMITIVE_CUBE = 0,
    BUILTIN_PRIMITIVE_PLANE,
    BUILTIN_PRIMITIVE_QUAD,
    BUILTIN_PRIMITIVE_UV_SPHERE,
    BUILTIN_PRIMITIVE_CYLINDER,
    BUILTIN_PRIMITIVE_COUNT
} BuiltinPrimitiveType;
